version: "2"
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/namecoin)
    goimports:
      local-prefixes:
        - github.com/namecoin
